---
title: "Statistical Learning"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(glmnet)
set.seed(1031)
```

## Try Lasso 

import and clean birth weight data 

```{r}
birthweight <- 
  read_csv("data/birthweight.csv") %>% 
  janitor::clean_names() %>% 
  mutate(
    babysex = 
        case_match(babysex,
            1 ~ "male",
            2 ~ "female"
        ),
    babysex = fct_infreq(babysex),
    frace = 
        case_match(frace,
            1 ~ "white",
            2 ~ "black", 
            3 ~ "asian", 
            4 ~ "puerto rican", 
            8 ~ "other"),
    frace = fct_infreq(frace),
    mrace = 
        case_match(mrace,
            1 ~ "white",
            2 ~ "black", 
            3 ~ "asian", 
            4 ~ "puerto rican",
            8 ~ "other"),
    mrace = fct_infreq(mrace)
    ) %>% 
  sample_n(200)
  
```

Construct inputs for `glmnet`

```{r}
x <- model.matrix(bwt ~., data = birthweight)[, -1]
y <- birthweight %>% pull(bwt)
```

Fit Lasso for Several Lambdas

```{r}
lambda <- 10^seq(-2, 2.75, by = 0.1) 

lasso_fit <-
  glmnet(x = x, y = y, lambda = lambda)

lasso_cv <- 
  cv.glmnet(x = x, y = y, lambda = lambda)
lambda_opt <- lasso_cv[["lambda.min"]]
```

Usual Lasso Plot 

```{r}
lasso_fit %>% 
  broom::tidy() %>% 
  filter(term != "(Intercept)") %>% 
  select(term, lambda, estimate) %>% 
  complete(term, lambda, fill = list(estimate = 0)) %>% 
  ggplot(aes(x = lambda, y = estimate, group = term, color = term)) + 
  geom_vline(xintercept = lambda_opt, color = "red") +
  geom_line()
```

```{r}
final_lasso_fit <- 
  glmnet(x = x, y = y, lambda = lambda_opt)

final_lasso_fit %>% 
  broom::tidy()
```


Look at CV results. 

```{r}
lasso_cv %>% 
  broom::tidy() %>% 
  ggplot(aes(x = log(lambda), y = estimate)) + geom_point()
```




